project:
  type: website

website:
  title: "Health Code Violation Awareness"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
        icon: "house"
      - href: Map.qmd
        text: Map
        icon: "map"
      - href: letter.qmd
        text: Write A Letter
        icon: "envelope"
      - text: More
        menu:
        - About.qmd
        - Data.qmd
  sidebar:
    tools:
      - icon: 0-circle
        href: https://observablehq.com/@cs-workspace?tab=notebooks
      - icon: github
        href: https://github.com/caramara81692/caramara81692.github.io

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true

editor: visual

